version: '1.0'
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: carrental
      MYSQL_DATABASE: carrental
    ports:
      - "3306:3306"

  webapi:
    container_name: webapi
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
     - "8081:80"
volumes:
  mysql:
  webapi:
  nginx: