spring:
  application:
    name: @artifactId@
  profiles: 
    active: @profileActive@
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

springfox:
  documentation:
    swagger:
      use-model-v3: false

server:
  port: 8080
  servlet:
    context-path: /@artifactId@