spring:
  application:
    name: @artifactId@
  profiles: 
    active: @profileActive@, environment
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

server:
  port: 8080
  servlet:
    context-path: /@artifactId@

logging:
  level:
    org.springframework.web: DEBUG