
server:
  port: 8081

momo:
  partnerCode: MOMOI3J920220921
  accessKey: yzp3lsHbJJifAkNU
  secretKey: CJLOBZMb1CpjqpDl9bhA9zqnCTv2ThSY
  endPoint: https://test-payment.momo.vn/v2/gateway/api/create
  returnUrl: http://localhost:8081/api/payment/momo-info
  notifyUrl: http://localhost:8080/ETrans/MoMoNotify