spring:
  application:
    name: @artifactId@
  profiles: 
    active: @profileActive@, environment
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

springfox:
  documentation:
    swagger:
      use-model-v3: false

server:
  port: 8080
  servlet:
    context-path: /@artifactId@

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
  file:
    name: @artifactId@.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"